export const post_types = {
  ADD_POST: 'ADD_POST',
  EDIT_POST: 'EDIT_POST',
  GET_POST: 'GET_POST',
  DELETE_POST: 'DELETE_POST',
  ADD_LIKE: 'ADD_LIKE',
  UN_LIKE: 'UN_LIKE',
  ADD_COMMENT: 'ADD_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  GET_SINGLE_POST: 'SINGLE_POST',
}
